export const CATEGORIES_ACTION_TYPES = {
	SET_CATEGORIES_FETCH_START: "categories/SET_CATEGORIES_FETCH_START",
	SET_CATEGORIES_FETCH_SUCCESS: "categories/SET_CATEGORIES_FETCH_SUCCESS",
	SET_CATEGORIES_FETCH_ERROR: "categories/SET_CATEGORIES_FETCH_ERROR",
};
