export const CATEGORIES_ACTION_TYPES = {
	CATEGORIES_FETCH_START: "categories/CATEGORIES_FETCH_START",
	CATEGORIES_FETCH_SUCCESS: "categories/CATEGORIES_FETCH_SUCCESS",
	CATEGORIES_FETCH_ERROR: "categories/CATEGORIES_FETCH_ERROR",
};
